### ISSUE TITLE
Hoverboard doesn't open on OS X

### ISSUE THREAD

**Issue by rothsandro** [elslooo/hoverboard#2]
The app doesn't start with OS X 10.11.6 (15G1217). There is no error message.

**Comment by elslooo** [comment]
Hi Sandro,

I just checked and you're right, it does crash on older macOS versions. 👎 

Fortunately, it was a minor bug. I fixed it and verified that it works on macOS 10.10.5 so if I interpolate correctly that would mean it will work on your Mac too.

[You can download the patched version here.](https://github.com/elslooo/hoverboard/releases/tag/1.0.1) Make sure to remove the old version first so they don't get mixed up.

Please let me know if this helps you!

Greetings,

Tim

**Comment by rothsandro** [comment]
Hello Tim

Great, the patched version works fine.

Regards,
Sandro
